name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test_and_formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Make script executable
        run: chmod +x code_quality.sh

      - name: Run code quality checks and tests
        run: ./code_quality.sh all

  deploy-dev:
    needs: test_and_formatting
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Serverless Framework
        run: npm install

      - name: Set Serverless Access Key
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Deploy to AWS (dev)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          COGNITO_USER_POOL_ID_DEV: ${{ secrets.COGNITO_USER_POOL_ID_DEV }}
          COGNITO_APP_CLIENT_ID_DEV: ${{ secrets.COGNITO_APP_CLIENT_ID_DEV }}
          SES_FROM_EMAIL_DEV: ${{ vars.SES_FROM_EMAIL_DEV }}
        run: npm run deploy:dev

  deploy-prod:
    needs: test_and_formatting
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Serverless Framework
        run: npm install

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set Serverless Access Key
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Deploy to AWS (prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          COGNITO_USER_POOL_ID_PROD: ${{ secrets.COGNITO_USER_POOL_ID_PROD }}
          COGNITO_APP_CLIENT_ID_PROD: ${{ secrets.COGNITO_APP_CLIENT_ID_PROD }}
          SES_FROM_EMAIL_PROD: ${{ vars.SES_FROM_EMAIL_PROD }}
        run: npm run deploy:prod
